import Image from "next/image";
import type { Metadata } from "next";
import { Btn, Eyebrow, WINNERS_HOME } from "@/components/ui";
import Form from "@/components/Form";
import Countdown from "@/components/Countdown";
export const metadata: Metadata = { title: "African Food Influencers Award" };
export default function Afia() {
  return (
    <>
      <section className="dark relative flex min-h-[720px] items-center pt-[88px] text-center" style={{ backgroundImage: "linear-gradient(180deg, rgba(0,0,0,0.2), rgba(0,0,0,0.7)), url(/img/Active-Hero-2026.png)", backgroundSize: "cover", backgroundPosition: "center" }}>
        <div className="container py-20"><Eyebrow>African Food Influencers Awards</Eyebrow><h1 className="mx-auto mt-6 max-w-4xl text-[length:var(--text-hero)]">Africa&apos;s Food Industry <span className="gold">Recognition Platform</span></h1><p className="display mt-6 text-[16px] text-white md:text-[22px]">AFIA 2026 — In Partnership with CAPA — Coming November 2026</p><p className="lede mx-auto mt-4 max-w-2xl text-white/85">Celebrating the chefs, entrepreneurs, storytellers, and leaders shaping Africa&apos;s culinary future.</p><Countdown to="2026-11-01T00:00:00+01:00" /><div className="mt-8"><Btn href="/about">Learn About AFIA</Btn></div></div>
      </section>
      <section className="section"><div className="container grid items-center gap-12 lg:grid-cols-2"><div><h2 className="text-[length:var(--text-h1)]">What is AFIA?</h2><p className="mt-5">The African Food Influencers Awards is Africa’s definitive recognition platform for excellence in food, culinary arts, and food industry leadership.</p><p className="mt-4">Organised annually, AFIA honours the individuals and brands making a measurable, lasting contribution to Africa’s food ecosystem — across culinary arts, entrepreneurship, media storytelling, and cultural preservation.</p><p className="mt-4">The awards are built on three principles that do not change: impact over popularity, independent jury, and zero pay-to-play.</p><h3 className="mt-6 text-[18px] text-[color:var(--afia-gold-600)]">AFIA 2026</h3><p className="mt-2">AFIA 2026 is convened by African Food Network in partnership with CAPA — Culinary Art Practitioners Association of Nigeria — as National Host and Chef Network Partner.</p></div><Image src="/img/AFIA.png" alt="AFIA" width={800} height={600} className="img-frame" /></div></section>
      <section className="dark section text-center"><div className="container max-w-2xl"><h2 className="text-[length:var(--text-h2)]">AFIA 2026 Nominations Are Opening Soon</h2><p className="mt-4 text-white/85">Know someone who has made a genuine, measurable contribution to Africa&apos;s food ecosystem? AFIA 2026 nominations open in November 2026. Be the first to know when they do.</p><div className="mt-6"><Form name="Notify me (AFIA)" submit="Notify Me" thanks="We will let you know."><input className="input h-[52px]" name="email" type="email" placeholder="Email" aria-label="Email" required /></Form></div></div></section>
      <section className="dark section border-t border-white/10 text-center"><div className="container"><Eyebrow>From the Inaugural Edition</Eyebrow><h2 className="mt-5 text-[length:var(--text-h1)]"><span className="gold">AFIA 2025</span> — The First Class</h2><p className="mx-auto mt-4 max-w-2xl text-white/85">In 2025, the African Food Influencers Awards held its inaugural edition — bringing together the first class of honourees recognised for their contribution to Africa&apos;s food ecosystem.</p><div className="mt-10 grid gap-6 text-left md:grid-cols-3">{WINNERS_HOME.map(([img, n, a, c, d]) => <div key={n}><Image src={`/img/${img}`} alt={n} width={400} height={500} className="aspect-[4/5] w-full rounded-xl object-cover object-top" /><h3 className="mt-4 text-[18px] text-white">{n}</h3><p className="display text-[15px] normal-case tracking-normal text-[color:var(--afia-gold-500)]">{a}</p><p className="display mt-1 text-[13px] text-white/70">{c}</p><p className="mt-2 text-[14px] text-white/80">{d}</p></div>)}</div><div className="mt-10"><Btn href="/winners/2025-winners">See All AFIA 2025 Winners</Btn></div></div></section>
      <section className="section text-center"><div className="container"><Eyebrow light>AFIA 2026 Partners</Eyebrow><h2 className="mt-5 text-[length:var(--text-h1)]">Delivered in Partnership</h2><div className="card-light mx-auto mt-10 grid max-w-4xl items-center gap-8 p-8 text-left md:grid-cols-[260px_1fr] md:p-10"><Image src="/img/CAPA.jpeg" alt="CAPA" width={260} height={130} className="mx-auto w-[220px] md:w-[260px]" /><div><h3 className="text-[18px] normal-case tracking-normal text-black">National Host and Chef Network Partner — AFIA 2026</h3><p className="mt-3 text-[14px]">AFIA 2026 is convened by African Food Network in partnership with CAPA as National Host and Chef Network Partner.</p><div className="mt-5"><Btn href="/partners" variant="outline-light">Explore Partnerships</Btn></div></div></div></div></section>
      <section className="dark section text-center"><div className="container"><h2 className="gold text-[length:var(--text-h1)]">Stay Connected to AFIA</h2><p className="mt-4 text-white/85">Be notified when the AFIA 2026 shortlist is announced and when the ceremony date is confirmed.</p><div className="mx-auto mt-8 max-w-[550px]"><Form name="Stay connected (AFIA page)" submit="Keep Me Updated" thanks="You are on the list."><input className="input h-[52px]" name="email" type="email" placeholder="Your Email" aria-label="Email" required /></Form><p className="mt-4 text-[13px] text-white/70">No spam. Unsubscribe at any time.</p></div></div></section>
    </>
  );
}
