export type Nominee = { name: string; logo?: string };
export const NOMINEES_2025: [string, Nominee[]][] = [
  ["Chef of the Year", [{ name: "Chef Hilda Baci (Nigeria)" }, { name: "Chef Dieuveil Malonga (Congo)" }, { name: "Chef Selassie Atadika (Ghana)" }, { name: "Chef Vusi Ndlovu (South Africa)" }]],
  ["Restaurant of the Year", [{ name: "Itan Test Kitchen (Lagos, Nigeria)", logo: "Itan.png" }, { name: "Midunu Accra (Ghana)", logo: "Midunu.png" }, { name: "Epicure Johannesburg (South Africa)", logo: "epicure_theone_logo.jpg" }, { name: "Nur Restaurant Fez (Morocco)", logo: "nur.png" }]],
  ["Street Food Champion", [{ name: "Iya Oyo (Abuja, Nigeria)" }, { name: "Mama Oliech Restaurant (Nairobi, Kenya)" }, { name: "Fulani Kitchen Street Dine Series (Guinea/Sierra Leone)" }, { name: "University of Suya (Lagos, Nigeria)" }]],
  ["Food Influencer of the Year", [{ name: "Sisi Yemmie (Nigeria)" }, { name: "Tolani Tayo-Osikoya (Nigeria)" }, { name: "Kaluhi Adagala (Kenya)" }, { name: "Kinorah Awini (Ghana)" }, { name: "Gina Ehikodi Ojo (Nigeria)" }]],
  ["Culinary Storyteller Award", [{ name: "Ozoz Sokoh (Nigeria)" }, { name: "Stephen Satterfield (USA/Ghana)" }, { name: "Imma Adamu (Cameroon/USA)" }, { name: "Ameyaw Debrah (Ghana)" }, { name: "Zoe Adjonyoh (Ghana/UK)" }]],
  ["African Food Brand of the Year", [{ name: "So Fresh (Nigeria)", logo: "sofreshLogo__.c59a42a232539ec1f776.png" }, { name: "AACE Foods (Nigeria)", logo: "AACE-Foods-Nigeria.webp" }, { name: "Yolélé Foods (Senegal/USA)", logo: "yolele.png" }, { name: "Nuli (Nigeria/USA)", logo: "Nuli-Nigeria_USA.png" }, { name: "Java Foods (Zambia)", logo: "Java-Foods-Zambia.jpg" }]],
  ["African Drinks Brand of the Year", [{ name: "Kasapreko Company Ltd (Ghana)", logo: "Kasapreko.avif" }, { name: "Rite Foods – Bigi & Fearless (Nigeria)", logo: "ritefoods_logo.jpg" }, { name: "Orijin – Guinness Nigeria (Nigeria)", logo: "orijin.jpg" }, { name: "Savanna Premium Cider (South Africa)", logo: "savanna-logo-png_seeklogo-260787.png" }, { name: "Mutzig Beer (Cameroon/DRC)", logo: "MUTZIG.webp" }]],
  ["Food Innovation & Entrepreneurship Award", [{ name: "Kola Masha – Babban Gona (Nigeria)" }, { name: "Wawira Njiru – Food for Education (Kenya)" }, { name: "Alloysius Attah – Farmerline (Ghana)" }, { name: "Uka Eje – ThriveAgric (Nigeria)" }, { name: "Monica Musonda – Java Foods (Zambia)" }]],
  ["Sustainability Champion Award", [{ name: "Chef Fatmata Binta (Guinea/Sierra Leone)" }, { name: "Dr Agnes Kalibata (Rwanda)" }, { name: "Ndidi Okonkwo Nwuneli (Nigeria)" }, { name: "Wawira Njiru (Kenya)" }, { name: "Chef Dieuveil Malonga (Congo/Rwanda)" }]],
  ["Community Impact Award", [{ name: "Michael Sunbola – Lagos Food Bank Initiative (Nigeria)" }, { name: "Elijah Amoo Addo – Food for All Africa (Ghana)" }, { name: "Isabelle Kamariza – Solid’Africa (Rwanda)" }, { name: "Amb. Gift Emmanuel Agbas – Promiseland Foundation (Nigeria)" }, { name: "Chef Ali Mandhry (Kenya)" }]],
  ["African Diaspora Food Voice", [{ name: "Pierre Thiam (Senegal/USA)" }, { name: "Marcus Samuelsson (Ethiopia/Sweden/USA)" }, { name: "Zoe Adjonyoh (Ghana/UK)" }, { name: "Eric Adjepong (Ghana/USA)" }, { name: "Imma Adamu – Immaculate Bites (Cameroon/USA)" }]],
  ["Rising Star in Food & Drinks", [{ name: "Chef Neo Nontso – Dine with Neo (South Africa)" }, { name: "Chef Tracy Nwapa – Òkàn Lagos (Nigeria)" }, { name: "Chef Aliyyah Musa – Zanzibar Kitchen Stories (Tanzania)" }, { name: "Chef Abdoulaye Faye – Dakar Street Grill (Senegal)" }]],
  ["Lifetime Achievement Award", [{ name: "Dr Lindiwe Majele Sibanda (Zimbabwe/South Africa)" }, { name: "Chef Christian Abégan (Cameroon)" }, { name: "Jenny Morris (South Africa)" }, { name: "Anto Cocagne (Gabon/France)" }, { name: "Dr Akinwumi Adesina (Nigeria)" }]],
];
export type Winner = { category: string; name: string; image?: string; bio: string };
export const WINNERS_2025: Winner[] = [
  { category: "Chef Of The Year", name: "Chef Hilda Baci", image: "Chef-Hilda-Baci.jpg", bio: "A global record-breaking chef whose achievements following her Guinness World Record and festival appearances have positioned Nigerian cuisine on the world stage. She is recognized for redefining culinary excellence and cultural expression both locally and globally." },
  { category: "Rising Star in Food & Drinks", name: "Chef Neo Nontso", image: "Chef-Neo-Nontso.webp", bio: "A fast-rising chef, cookbook author, and TV personality promoting modern South African cuisine to new audiences. She represents the next generation of African food and drink talent making waves in the industry." },
  { category: "Restaurant of the Year", name: "Nur Restaurant Fez", image: "nur.png", bio: "Led by Chef Najat Kaanache, this award-winning Moroccan restaurant offers a tasting menu experience that is regularly ranked among the best in Africa. It is a venue that best represents quality, service, and authentic African food culture." },
  { category: "Food Influencer of The Year", name: "Tolani Tayo-Osikoya", image: "Tolani-Tayo.jpg", bio: "A highly influential culinary content creator with millions of followers, Tolani is recognized for her high-quality visuals and step-by-step cooking tutorials. She is a leading digital voice driving the African food conversation globally." },
  { category: "Culinary Storyteller Award", name: "Ameyaw Debrah", image: "Ameyaw-Debrah-Ghana.png", bio: "An influential journalist and publisher, Ameyaw spotlights African chefs, festivals, and creators through Ameyaw TV and digital media. He is celebrated for documenting Africa's food stories and shaping how African food is seen and understood globally." },
  { category: "African Food Brand of The Year", name: "AACE Foods", image: "AACE-Foods-Nigeria.webp", bio: "An indigenous food processing company founded by Ndidi and Mezuo Nwuneli, AACE Foods is known for fortifying local spices and grains. They are a consumer brand leading in market influence and cultural pride." },
  { category: "African Drinks Brand of the Year", name: "Savanna Premium Cider", image: "savanna-logo-png_seeklogo-260787.png", bio: "A leading African cider brand with continental reach and premium market positioning. This award celebrates their innovation in African beverage culture." },
  { category: "Food Innovation & Entrepreneurship Award", name: "Alloysius Attah", image: "Alloysius-Attah.jpg", bio: "An Agritech entrepreneur using data and digital tools to support smallholder farmers across West Africa. Alloysius is recognized for reshaping the African food business through technology-backed solutions." },
  { category: "Sustainability Champion Award", name: "Ndidi Okonkwo Nwuneli", image: "Ndidi-Okonkwo-Nwuneli.jpg", bio: "The Co-founder of Sahel Consulting and AACE Foods, Ndidi is a leading voice for food systems transformation in Africa. She is honored for promoting eco-friendly food systems and climate-smart agriculture." },
  { category: "Community Impact Award", name: "Michael Sunbola", image: "Michael-Sunbola_Leaders-Africa-2019-853-scaled.webp", bio: "Through the Lagos Food Bank Initiative, Michael provides regular food aid and nutrition programs for underprivileged families. He is honored for using food to support communities and fight hunger." },
  { category: "African Diaspora Food Voice", name: "Zoe Adjonyoh", image: "Zoe-Adjonyoh.jpg", bio: "The author of \"Zoe's Ghana Kitchen,\" she is a key figure in redefining African food culture in Europe. Zoe represents African cuisine globally through her content and advocacy." },
  { category: "Lifetime Achievement Award", name: "Dr. Akinwumi Adesina", image: "AA.webp", bio: "As President of the African Development Bank, Dr. Adesina has been instrumental in financing and promoting Africa's food security agenda for over two decades. This award honors his decades of consistent contribution to Africa's food and agricultural progress." },
  { category: "Plant-Based Influencer of the Year", name: "Ebenezer Odeniyi", image: "Ebenezer-Odeniyi.jpg", bio: "As a leading advocate for plant-based African cuisine, Ebenezer Odeniyi (Veganezer) has transformed how Africa and the diaspora view vegan food. This award recognises his dedication to promoting wellness, sustainability, and a modern culinary identity rooted in Africa's rich heritage." },
  { category: "Special Recognition Award", name: "Beke Igwe", image: "Beke-Igwe.jpeg", bio: "Beke Igwe is the Director of Beke's Kitchen Limited (which also operates as Bekes Caterers) and identifies herself as a \"foodpreneur\" rather than just a chef. She has over 15 years of experience in the hospitality industry, specializing in authentic African and Caribbean gourmet catering services across the UK and the Middle East." },
];
